name: trdltool
description: "TRDLtools. Specialized tools for rail professionals."
publish_to: 'none'

version: 0.0.2+0

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^8.0.1
  intl: ^0.20.2
  just_audio: ^0.10.4
  logger: ^2.6.1
  lucide_icons_flutter: ^3.1.4
  package_info_plus: ^9.0.0
  signals: ^6.0.2
  toastification: ^3.0.3
  url_launcher: ^6.3.2
  wakelock_plus: ^1.4.0
  web: ^1.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/wav/beltoon.wav
    - assets/wav/bo_alarm.wav
    - assets/wav/mcn_alarm.wav
    - assets/icons/trdlToolsIcon.png
